<?php
namespace gc\wp\reference;
/**
 * GC_ReferenceWidget
 *
 * This is a reference widget class that demonstrates the widget lifecycle.
 *
 * @see widget-display.php
 * @see widget-form.php
 * @link https://developer.wordpress.org/reference/functions/register_widget/
 */
class Widget extends \WP_Widget {

	function __construct() {
		// Create the options we'll provide to the parent class' constructor.
		$widget_opts = array(
			/**
			 * the class name added to the HTML tag wrapping the widget when it's displayed (It may show up in a
			 * <div>, <aside>, <li>, or other HTML tag.)
			 */
			'classname' => 'gc_reference_widget',
			/**
			 * displayed on the widget dashboard below the widget name
			 */
			'description' => 'Example widget defined by the plugin\'s widget class.'
		);
		parent::__construct(
			'gc_reference_widget', // the widget's HTML ID prefix
			'GC Reference Widget', // the widget's name
			$widget_opts);
	}

	/**
	 * The widget's HTML output.
	 *
	 * @see WP_Widget::widget()
	 *
	 * @param array $args     Display arguments including before_title, after_title,
	 *                        before_widget, and after_widget.
	 * @param array $instance The settings for the particular instance of the widget.
	 */
	function widget( $args, $instance ) {
		// Extract the $args parameters to store some global theme values like $before_widget and $after_widget.
		// (These variables can be used by theme developers to customize what code will wrap the widget.)
		extract($args);
		echo $args['before_widget'];
		// Include the HTML generated by the widget's display page.
		include "widget-display.php";
		// Tack on whatever the current theme believes should come after the widget.
		echo $args['after_widget'];
	}

	/**
	 * The widget update handler.
	 *
	 * @see WP_Widget::update()
	 *
	 * @param array $new_instance The new instance of the widget.
	 * @param array $old_instance The old instance of the widget.
	 * @return array The updated instance of the widget.
	 */
	function update( $new_instance, $old_instance ) {
		$instance = $old_instance;
		$instance['title']=sanitize_text_field($new_instance['title']);
		$instance['name']=sanitize_text_field($new_instance['name']);
		$instance['bio']=sanitize_text_field($new_instance['bio']);
		return $instance;
	}

	/**
	 * Output the admin widget options form HTML.
	 *
	 * @param array $instance The current widget settings.
	 * @return string The HTML markup for the form.
	 */
	function form( $instance ) {
		// Provide default widget properties.
		$defaults = array(
			'title' => 'My Biography',
			'name' => 'Dudley Do-Right',
			'bio' => 'I am a royal Canadian Mountie.'
		);
		// Combine the defaults with the properties in the current widget settings.
		$instance = wp_parse_args((array)$instance, $defaults);
		$title = $instance['title'];
		$name = $instance['name'];
		$bio = $instance['bio'];
		// Provide HTML to the caller.
		include "widget-form.php";
	}
}